services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  ai-note-searcher:
    build: .
    volumes:
      - /Volumes/Development/Notebook:/app/notebook:ro
    environment:
      - QDRANT_URL=http://qdrant:6333
      - NOTEBOOK_PATH=/app/notebook
    depends_on:
      - qdrant
    restart: unless-stopped

